version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rdTemp
    ports:
      - 1433:1433
    volumes:
      - ./script:/opt/workspace/script
      - ./DDL:/opt/workspace/DDL
      - ./DML:/opt/workspace/DML

